apiVersion: v1
kind: Service
metadata:
  labels:
    razee/watch-resource: detail
    run: hello-app
  name: hello-svc
  namespace: kitch
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-app
  type: LoadBalancer
